### ISSUE TITLE
F8 prints answer before timer is finished

### ISSUE THREAD

**Issue by Orthad0x** [Jesper-Hustad/NoPixel-minigame#19]
The main issue i have is when you activate the trigger, You can press F8 and get the answer before the minigame timer has finished.

Also how do i trigger correctly? Im triggering the event and no matter the outcome (pass or fail) it treats it as a success everytime.

**Comment by RealDebugg** [comment]
I'll send a pr fix for this on thursday or friday. That is odd...

**Comment by RealDebugg** [comment]
Might have found the issue. I’ll be running some tests tomorrow:)

**Comment by RealDebugg** [comment]
should be fixed, please update me :)
