### ISSUE TITLE
Colour yellow and orange are very similar

### ISSUE THREAD

**Issue by zarubikon** [Jesper-Hustad/NoPixel-minigame#2]
Love the game and the code. A very simple fix that I would really appreciate is changing the colour orange within the game. The orange is very similar to the yellow and when looking quickly it is very easy to mix them up. I would suggest keeping the yellow colour and changing the orange to a more vibrant colour.

**Comment by Jesper-Hustad** [comment]
The colors are picked directly from the NoPixel GTA servers version. I am sorry if this causes confusion, not to mention for all color blind people this is especially not accessible, but i am trying to stay true to that version.

If you look in `src/puzzle-factory.js` you can see the colors set through the variable `COLORS`:

```javascript
const COLORS = {
    'black' : 'black',
    'white' : 'white', 
    'blue' : '#1991F9',
    'red' : '#8C0C00',
    'yellow' : '#FFE335',
    'orange' : '#FF9900',
    'green' : '#46A04F',
    'purple' : '#A43AB5',
}
```
Feel free to fork the repository and change the colors to your liking! 😊

If you have the time and want to i would accept a pull request for a color blind version, i will add that as an issue!
