### ISSUE TITLE
Puzzle always returns "failed"

### ISSUE THREAD

**Issue by pandire** [Jesper-Hustad/NoPixel-minigame#21]
getting a issue of when i pass the puzzle it says i failed

**Comment by Jesper-Hustad** [comment]
Is this related to the FiveM version?

**Comment by pandire** [comment]
> Is this related to the FiveM version?

Im not to sure but it types in chat when i pass saying fail,

**Comment by Jesper-Hustad** [comment]
This is a known issue @RealDebugg is working on a solution for it.  
If you have the knowledge of working with Fivem and javascript feel free to fix it!

**Comment by pandire** [comment]
> This is a known issue @RealDebugg is working on a solution for it.
> If you have the knowledge of working with Fivem and javascript feel free to fix it!

Ok thank you :)

**Comment by RealDebugg** [comment]
Should have been fixed now
