### ISSUE TITLE
Answer logged to console

### ISSUE THREAD

**Issue by kyleskkrt** [Jesper-Hustad/NoPixel-minigame#22]
Sorry if im doing this wrong but how do i remove it saying the answers in my F8 Console please help

**Comment by swxy** [comment]
remove console.log in the js

**Comment by Jesper-Hustad** [comment]
This seems like a logical thing to add for the FiveM version. Feel free to make a pull request.

**Comment by RealDebugg** [comment]
fixed for ya 😄
