### ISSUE TITLE
mouse stuck

### ISSUE THREAD

**Issue by cowardtv** [Jesper-Hustad/NoPixel-minigame#24]
soo when you start the hack everything is good but when you finish either by success or a fail whenever you finish the hack the menu goes down but your mouse stays stuck and you get a block error that the html blocks you from finishing it
just like this below
![Screenshot_1](https://user-images.githubusercontent.com/25543568/123515833-cc43b480-d6a1-11eb-87bd-000bb560865a.png)

it only happened in this new days maybe since a lot of people use it and its blocking ip's idk

**Comment by Jesper-Hustad** [comment]
It seems like your code loading the mini game cfx-nui-hacking is run over https while this is being called using http

Should have nothing to do with IP as this is running locally (no internet required).

Anyone else with FiveM knowledge who can take a look at this?

**Comment by cowardtv** [comment]
i solved it .. it was my issue i had instead of https://hacking/callback i had http://hacking/callback
and putting a s solved it

**Comment by AverageGermanUser** [comment]
Hey adding the s so it is https://hacking/callback instead of http://hacking/callback, does fix the error of 'Mixed Content'. But for some reason the mouse still gets stuck with the second error on the picture 'Uncaught (in promise) TypeError'. Any idea how to fix that?

**Comment by Jesper-Hustad** [comment]
> Hey adding the s so it is https://hacking/callback instead of http://hacking/callback, does fix the error of 'Mixed Content'. But for some reason the mouse still gets stuck with the second error on the picture 'Uncaught (in promise) TypeError'. Any idea how to fix that?

Hi, can you make a new issue with your problem. Doing that will make it a lot easier to track issues, thanks!
