### ISSUE TITLE
Error F8

### ISSUE THREAD

**Issue by n3x98** [Jesper-Hustad/NoPixel-minigame#26]
Can't use mouse, error F8: 
![](https://i.imgur.com/isBoyoY.png)

**Comment by Jesper-Hustad** [comment]
Does this help?  
>In script.js the fetch link was missing the main folders name

**Comment by n3x98** [comment]
The folder name is hacking, same in js

**Comment by AverageGermanUser** [comment]
you need to add an 's' so it is https://hacking/callback and not http://hacking/callback

**Comment by Jesper-Hustad** [comment]
What would be the best way to solve this so people stop having this problem?
Change the README to warn about this?
What do you guys suggest?

**Comment by n3x98** [comment]
Edit : 

.js line 50 and add this https://hacking/callback

https://i.imgur.com/Sa0Nlk3.png

**Comment by Jesper-Hustad** [comment]
OK, the change is added. Thanks for the help!
