### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TaaVetP** [Jesper-Hustad/NoPixel-minigame#27]
![image](https://user-images.githubusercontent.com/81780337/124020337-d55eb980-d9f2-11eb-8e40-04e45b17cbc4.png)
happens after completeing/failing
and the mouse is stuck

**Comment by Jesper-Hustad** [comment]
See #26 already has a solution

**Comment by Jesper-Hustad** [comment]
This has now been fixed in the latest version :)
