### ISSUE TITLE
Error during NUI callback: attempt to call a nil value

### ISSUE THREAD

**Issue by TaaVetP** [Jesper-Hustad/NoPixel-minigame#28]
This error occurs:
![image](https://user-images.githubusercontent.com/81780337/124044379-f8e72b80-da15-11eb-9515-9187c34a8bab.png)

**Comment by RealDebugg** [comment]
I'll try and rework the whole system on Wednesday :)

**Comment by RealDebugg** [comment]
Should be fixed, haven't tested it though. Its sampled code.

**Comment by RealDebugg** [comment]
Tested, fixed
