### ISSUE TITLE
[Puzzle / FiveM]: Puzzle

### ISSUE THREAD

**Issue by owaisahmed121** [Jesper-Hustad/NoPixel-minigame#29]
⬇ DELETE THIS TEXT ⬇
I'm sorry this maybe unrelated but idk how else to reach out to you. Is there anyway you could recreate the chip bank hack where you have to match constant code blocks in a grid? It's best described as the Alpha protocol hack minigame.
⬆ DELETE THIS TEXT ⬆

**Comment by Jesper-Hustad** [comment]
Sorry about not having contact information, i should fix that.

Unfortunately i don't have time for that right now.

Sorry that i can't be off help!
