### ISSUE TITLE
[Puzzle / FiveM]: Bugged 'undefined' answer option

### ISSUE THREAD

**Issue by symonxdd** [Jesper-Hustad/NoPixel-minigame#31]
Something went wrong with the game. Sometimes it wrongfully says that the answer was wrong, while it was right.
Instead of the right one it says it should have been undefined. Please see the screenshot.

![image](https://user-images.githubusercontent.com/45405238/128408690-12f1268e-910e-41cd-8990-381369b11c5a.png)

**Comment by Jesper-Hustad** [comment]
Must have accidentally screwed something up while adding language support. I will look into this, thanks for notifying!

**Comment by symonxdd** [comment]
@Jesper-Hustad Thank you & np! 👍
