### ISSUE TITLE
[Puzzle / FiveM]: Failure to fetch?

### ISSUE THREAD

**Issue by shmoodlepoop** [Jesper-Hustad/NoPixel-minigame#34]
Hi, I keep getting this error when the hack fails or when it has been completed.. I noticed in the script.js that there is a fetch for the hacking callback but not for the index. Ive never written in JS and am only starting to learn lua, so any help you could offer would be great thanks!
![NoPixelHackError](https://user-images.githubusercontent.com/90508561/132946461-2857be4c-2f86-473b-9ed2-e8c4cf09ffbf.PNG)

**Comment by RealDebugg** [comment]
Are you still having this issue? Haven't seen any other issues opened for this...

**Comment by shmoodlepoop** [comment]
yes im still having the issue... Ive started trying to learn a little bit of JS in hopes ill come across my issue at some point, but have not gotten far (working) anything else i should attach that may be useful?

**Comment by RealDebugg** [comment]
Try attaching an image of your nui_devtools console. Might show some more in depth explanation about the issue and what line might be causing it

**Comment by RealDebugg** [comment]
If you renamed the resource, make sure you change the post events in script.js too

**Comment by RealDebugg** [comment]
Quick question. Does this error still occurred when changing the name to "hacking"? Also, if you haven't already. I recently pushed an update to the script that fixes some older issues

**Comment by shmoodlepoop** [comment]
Yes I updated and left the name as hacking, changed the name in my server cfg and the script stopped working altogether.. provided no errors that I could find... I switched back to the version I had previously  installed (changing the name did fix it Duh thank you) but, now I receive this now after completing the hack... 

![NpHackNilError](https://user-images.githubusercontent.com/90508561/135699509-c51e95c0-5b7c-4144-affe-94d5900e8753.PNG) 

I feel dumb asking so many questions but its the only way to learn so thanks for your patience :)

**Comment by shmoodlepoop** [comment]
Also I have never used the devtools console... (Extremely new to coding, using this as a project to learn) Don't quite know how to find it. Is it a command?

**Comment by RealDebugg** [comment]
In your f8 console, to open devtools type: nui_devTools

It should open up a chrome inspector. There should be an option for console in there

**Comment by RealDebugg** [comment]
> Yes I updated and left the name as hacking, changed the name in my server cfg and the script stopped working altogether.. provided no errors that I could find... I switched back to the version I had previously installed (changing the name did fix it Duh thank you) but, now I receive this now after completing the hack...
> 
> ![NpHackNilError](https://user-images.githubusercontent.com/90508561/135699509-c51e95c0-5b7c-4144-affe-94d5900e8753.PNG)
> 
> I feel dumb asking so many questions but its the only way to learn so thanks for your patience :)

The updated version uses a different way to be triggered, I added a command to test it, you can copy the code from that, check if that works

**Comment by shmoodlepoop** [comment]
Oh got it okay thank you for the tip! ill do some messing around with it!

**Comment by Jesper-Hustad** [comment]
Awesome to see people using this project to learn coding ☺️

A lot of the way things work on GitHub may be a bit weird for new users, but it makes a lot of sense if you use the git program. Can take a bit of time tough.

Definitely don't get discouraged with things being difficult. Learning to code is just hitting a brick wall again and again, but always getting trough them no matter how confusing and hard it becomes.

Btw if there is any feedback on edits that can be made to the instruction text i would be happy to add them. I feel like a lot of the issues that people are facing could be remedied with better instructions targeting people new to the FiveM modding scene.

**Comment by shmoodlepoop** [comment]
appretiate all your help!
