### ISSUE TITLE
[Puzzle / FiveM]: TITLE HERE

### ISSUE THREAD

**Issue by tixyy** [Jesper-Hustad/NoPixel-minigame#43]
Describe the issue, go into details. Describe the issue, go into details. Dont know where to put it i am very bad at coding. I want an Norwegian as an language becuse i know many pepole that want this and what to pratice it to get good on the Norwegian RP servers

**Comment by Jesper-Hustad** [comment]
Funnily enough I'm Norwegian myself so shouldn't be to big of a problem

**Comment by Jesper-Hustad** [comment]
Norwegian and many other languages are now supported.
