### ISSUE TITLE
[Puzzle / FiveM]: Please make this Colorblind Friendly

### ISSUE THREAD

**Issue by Creeamy** [Jesper-Hustad/NoPixel-minigame#50]
If you have some sort of colorblindness like me (red/green) doing the hack can be impossible sometimes because the colors red/orange/yellow are really hard to differentiate and so you fail it simply because you can't tell which one is which. NoPixel does a great job of using shades of all colors that work for someone with colorblindness. You don't need some sort of colorblind mode the colors would just need to be changed so that it is easier to differentiate. If you wanted to you could use the NoPixel colors directly or just make the reds oranges and yellows far more different from each other while still being their respective colors. This is a really big issue for colorblind people even though their not the majority. Thanks so much for reading this!

The photo below is whats used in NoPixel
![IMG_1673](https://user-images.githubusercontent.com/101856131/158942222-eff7f8b2-0c95-4612-bd31-a1eb1024c3e9.jpg)

**Comment by Jesper-Hustad** [comment]
This is one of the first issues i added 11 months ago: #3

Totally agree with you.

If the colors on nopixel are better that sounds like an easy fix to implement.

**Comment by Jesper-Hustad** [comment]
Is there some resource online where i can find the colors used on nopixel?

**Comment by Creeamy** [comment]
https://sharkiller.ddns.net/nopixel_minigame/

https://github.com/sharkiller/nopixel_minigame

Sharkkillers version is exactly the same as used in NoPixel. That’s what I would look at.

**Comment by Jesper-Hustad** [comment]
Thanks so much, that was a good resource.
Found out there was a bug preventing the updated colors, it was actually just using the color names and not the predefined hex values.  
It should be fixed now 👍
