### ISSUE TITLE
German Language on ur Github page isnt working

### ISSUE THREAD

**Issue by NicoStr3** [Jesper-Hustad/NoPixel-minigame#54]
Whenever i choose the german language (on https://jesper-hustad.github.io/NoPixel-minigame/index), it freezes and doesnt let me do anything anymore.

Just wanted to tell you incase you didnt know.

**Comment by Jesper-Hustad** [comment]
Thanks for the bug report.  
Was an issue with google translate.  
It's supposed to only translate the words, but also translated the code `SHAPES` to `FORMEN`.  
Fixed now

**Comment by Jesper-Hustad** [comment]
Old version may be cached by your browser, so delete the cache if you are not getting the updated version.
https://www.fvsu.edu/how-to-clear-your-browser-cache/
