### ISSUE TITLE
Capitalized responses should be valid

### ISSUE THREAD

**Issue by lukadd16** [Jesper-Hustad/NoPixel-minigame#6]
The minigame should accept capitalized words like the version in NoPixel does. See the below image for what I mean.

![image](https://user-images.githubusercontent.com/58280822/117558784-2931cf80-b04e-11eb-9cbd-5f7efd5391f2.png)

**Comment by Jesper-Hustad** [comment]
Can only the first letter be capitalized or can a correct answer have all letters capitalized?

**Comment by lukadd16** [comment]
From the streamers I've been watching, I've only ever seen two combinations (both of which are accepted by the system): all lowercase (e.g. [xQc](https://youtu.be/I1ezTysqAno?t=344)) or first letter of each word capitalized (e.g. [Randy](https://youtu.be/zK729BEUkrE?t=161)). Admittedly it'd be a bit odd for somebody to be typing in all caps or with mixed casing throughout a word, so it's pretty unlikely that any clips exist demonstrating this.

That being said, I don't think it's unreasonable to assume that the version of the minigame used in NoPixel accepts mixed casing since ultimately all that matters is whether the hacker entered the correct word or not.

**Comment by Jesper-Hustad** [comment]
Alright, should be fixed now.
Your response is highly appreciated 🙏

**Comment by Jesper-Hustad** [comment]
Alright, should be fixed now.
Your response is highly appreciated 🙏
